# Generated by Django 5.2.1 on 2025-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_officelocation_attendance_date_attendance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officelocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
